import { Component, OnInit } from '@angular/core';
import { ModelLoaderService } from "@modules/engine/core/base/model-loader.service";
import { FormBuilder, Validators } from "@angular/forms";

export interface File{
  name: string,
  path: string,
  [propName: string]: any;
}

@Component({
  selector: 'adventure-model-loader',
  templateUrl: './model-loader.component.html',
  styleUrls: ['./model-loader.component.scss']
})
export class ModelLoaderComponent implements OnInit {

  selectedModel;

  modelsRaw: string[] = [
    "/assets/models/polygon-knights/Models/Characters/Villain.fbx",
    "/assets/models/polygon-knights/Models/SM_Wep_Broadsword_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Wep_Halberd_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Wep_Rapier_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Wep_Shield_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Wep_Shield_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Wep_Shield_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Wep_Shield_04.fbx",
    "/assets/models/polygon-knights/Models/SM_Wep_Zweihander_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_ArrowSlit_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_ArrowSlit_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Arrow_Slit_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Door_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Door_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Flag_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Flagpole_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Iron_Gate_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Pillar_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Roof_Spire_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Roof_Spire_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_01_Lite.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_02_Lite.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_03_Lite.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_04.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_04_Lite.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_Base_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_Base_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_Mini_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_Mini_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_Mini_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_Mini_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_Round_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_Round_01_Lite.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_Round_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_Round_02_Lite.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_Round_Top_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_Round_Top_01_Lite.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_Round_Top_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_Top_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_Top_01_Lite.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_Top_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_Wall_Top_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_Wall_Top_01_Lite.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Tower_Wall_Top_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Wall_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Wall_01_Lite.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Wall_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Wall_Gate_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Wall_Gate_01_Lite.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Wall_Gate_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Wood_Battlement_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Wood_Battlement_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Wood_Battlement_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Wood_Battlement_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Wood_Battlement_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Wood_Battlement_03_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Wood_Battlement_04.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Wood_Battlement_04_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Wood_Detal_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Castle_Wood_Detal_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Door_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Door_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Extension_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Extension_01_Lite.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Extension_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Room_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Room_01_Lite.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Room_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Room_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Room_02_Lite.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Room_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Room_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Room_03_Lite.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Room_03_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Tower_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Tower_01_Lite.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Tower_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Tower_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Tower_02_Lite.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Tower_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Tower_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Tower_03_Lite.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_TowerBase_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_TowerBase_01_Lite.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Church_Window_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Chimney_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Chimney_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Chimney_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Chimney_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Chimney_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Chimney_03_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Chimney_04.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Chimney_04_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Chimney_05.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Chimney_05_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Door_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Door_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Door_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Door_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Door_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Door_03_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Door_04.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Door_04_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Extension_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Extension_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Extension_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Extension_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Foundation_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Foundation_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Foundation_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Foundation_04.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Foundation_05.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Foundation_06.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Foundation_07.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Foundation_Beams_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_FoundationRock_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Room_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Room_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Room_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Room_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Room_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Room_03_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Room_04.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Room_04_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Room_05.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Room_05_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Room_06.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Room_06_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Room_07.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Room_07_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomRound_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomRound_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomRound_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomRound_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTall_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTall_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTall_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTall_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTall_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTall_03_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTall_04.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTall_04_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTall_05.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTall_05_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTall_06.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTall_06_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTop_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTop_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTop_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTop_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTop_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTop_03_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTop_04.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTop_04_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTop_05.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTop_05_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTop_06.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTop_06_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTop_07.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_RoomTop_07_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_StepsSmall_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_StepsSmall_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_TopRoomSmall_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_TopRoomSmall_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_TopRoomSmall_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_TopRoomSmall_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_TopRoomSmall_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_TopRoomSmall_03_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_TopRoomSmall_04.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_TopRoomSmall_04_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_TopRoomSmall_05.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_TopRoomSmall_05_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_TopRoomSmall_06.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_TopRoomSmall_06_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_TopRoomSmall_07.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_TopRoomSmall_07_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Tower_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Tower_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Window_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Window_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Window_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Window_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Window_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Window_03_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Window_04.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Window_04_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Window_05.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_House_Window_05_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Leanto_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Leanto_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Rockwall_Archway_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Rockwall_Archway_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Rockwall_StairArchway_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Rockwall_StairArchway_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Rockwall_Stairs_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Rockwall_Stairs_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Rockwall_Straight_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Rockwall_Straight_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_StairsLarge_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_StairsLarge_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_StairsLarge_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_StairsLarge_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_StairsLarge_Corner_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_StairsLarge_Corner_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_StairsLarge_Corner_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_StairsLarge_Corner_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Tent_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Tent_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Tent_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Tent_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Tent_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Tent_03_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Village_Well_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Village_Well_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Bld_Well_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Canal_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Canal_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Canal_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Canal_Block_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Canal_Bridge_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Canal_Bridge_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Cliff_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Cliff_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Cloud_06.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Flower_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Grass_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_GroundMound_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_GroundMound_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_MountainGrass_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_MountainGrass_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_MountainSnow_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_MountainSnow_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Cobble_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Cobble_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Cobble_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Cobble_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Cobble_Stone_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Dirt_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Dirt_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Dirt_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Dirt_04.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Dirt_05.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Dirt_06.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Snow_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Stone_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Stone_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Stone_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Stone_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Stone_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Stone_03_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Tile_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Tile_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Tile_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Tile_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Tile_Corner_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Path_Tile_Corner_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_RockPile_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_RockPile_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_RockPile_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_RockPile_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_RockPile_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_RockPile_03_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Tile_Dirt_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Tile_Grass_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Tile_Snow_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Tile_Water_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Tree_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Tree_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Tree_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Tree_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Tree_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Tree_03_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Tree_Twisted_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Tree_Twisted_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Tree_Twisted_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Env_Tree_Twisted_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Banner_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Banner_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Banner_03.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Beam_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Brazier_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Brazier_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_CampFire_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Cart_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Cart_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_CartHay_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_CartHay_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_CartWheel_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Crate_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Crate_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Fence_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Fence_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Fence_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Fence_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Grate_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Grate_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Gravestone_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Gravestone_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Gravestone_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Gravestone_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Guillotine_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Guillotine_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Lampost_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Lampost_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Plinth_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Plinth_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Plinth_02.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Plinth_02_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Rowboat_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Rowboat_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_ShopSign_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_ShopSign_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Statue_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Statue_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Statue_Base_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Statue_Base_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Trapdoor_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Trapdoor_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_WaterWheel_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_WaterWheel_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_WaterWheel_Support_01.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_WaterWheel_Support_01_Snow.fbx",
    "/assets/models/polygon-knights/Models/SM_Prop_Weathervane_01.fbx"
  ]

  texturesRaw: string[] = [
    "/assets/models/polygon-knights/Textures/Characters_Texture_Black.png",
    "/assets/models/polygon-knights/Textures/Characters_Texture_Blue.png",
    "/assets/models/polygon-knights/Textures/Characters_Texture_Orange.png",
    "/assets/models/polygon-knights/Textures/Characters_Texture_Yellow.png",
    "/assets/models/polygon-knights/Textures/Texture_01.png",
    "/assets/models/polygon-knights/Textures/Texture_01_Dark.png",
    "/assets/models/polygon-knights/Textures/Texture_01_Swap_Snow_To_Grass.png",
    "/assets/models/polygon-knights/Textures/Texture_Alt_02.png",
    "/assets/models/polygon-knights/Textures/Texture_Alt_02_Dark.png",
    "/assets/models/polygon-knights/Textures/Texture_Alt_03.png",
    "/assets/models/polygon-knights/Textures/Texture_Alt_03_Dark.png",
    "/assets/models/polygon-knights/Textures/Texture_Alt_04.png",
    "/assets/models/polygon-knights/Textures/Texture_Alt_04_Dark.png"
  ];

  modelForm = this.formBuilder.group({
    model: ['', [Validators.required]],
    texturePath: ['', [Validators.required]],
    size: [1, [Validators.required]],
    vector: this.formBuilder.group({
      x: ['', [Validators.required]],
      y: ['', [Validators.required]],
      z: ['', [Validators.required]]
    })
  });

  models: File[] = [];

  textures: File[] = [];


  //TODO: вынести в отдельную
  public getFileName(path) {
    return path.match(/[-_\w]+[.][\w]+$/i)[0];
  }

  constructor(
    private formBuilder: FormBuilder,
    private modelLoaderService: ModelLoaderService
  ) {}

  get formValue() {
    return this.modelForm.value as any;
  }

  submitForm() {
    this.modelLoaderService.loadModel(this.formValue);
  }

  ngOnInit() {
    this.modelsRaw.map((value) => {
      this.models.push({
        name: this.getFileName(value),
        path: value
      })
    });

    this.texturesRaw.map((value) => {
      this.textures.push({
        name: this.getFileName(value),
        path: value
      })
    });
  }

}
